IMAGE_SIZE      = (299, 299)
MAX_VOCAB_SIZE  = 2000000
SEQ_LENGTH      = 25
EMBED_DIM       = 512
NUM_HEADS       = 6
FF_DIM          = 1024
SHUFFLE_DIM     = 512
BATCH_SIZE      = 64
EPOCHS          = 1
VERBOSE         = True

REDUCE_DATASET  = False
NUM_TRAIN_IMG   = 68363
NUM_VALID_IMG   = 20000
TRAIN_AUGMENT   = True
VALID_AUGMENT   = False
TEST_DATASET    = False
SAVE_DIR        = 'output'
